#!/usr/bin/env bash
#
# End-to-end signing check against third-party tools.
#
# Every other test in this repo verifies underskrift's output with underskrift.
# This one signs a PDF and hands it to implementations that share no code with
# us: poppler for signature and trust validation, qpdf for structure, openssl
# for the certificate chain.
#
# Usage:
#   tests/e2e-verify.sh [document.pdf]
#
# With no argument a document is generated with typst, falling back to the
# committed sample fixture when typst is unavailable.
#
# Requires: pdfsig (poppler-utils), qpdf, certutil (libnss3-tools), openssl.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fixtures="$repo_root/tests/fixtures"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "  ok — $*"; }

for tool in pdfsig qpdf certutil openssl; do
    command -v "$tool" >/dev/null || fail "$tool not found"
done

# The fixture CA is regenerated by gen-test-fixtures.sh on every run, so the
# trust store has to be built from the chain that actually signed this file.
# Pointing it at a stale ca_cert.pem yields "Certificate issuer is unknown",
# which looks like a signing bug and is not one.
[ -f "$fixtures/signer.p12" ] || fail "missing $fixtures/signer.p12 — run gen-test-fixtures.sh from tests/fixtures"

# --- the document under test -------------------------------------------------

if [ $# -ge 1 ]; then
    source_pdf="$1"
elif command -v typst >/dev/null; then
    cat > "$work/doc.typ" <<'TYP'
#set page(width: 210mm, height: 297mm, margin: 20mm)
#set text(size: 11pt)
= Interoperability test document
Generated by Typst, signed by underskrift, verified by poppler.
#lorem(80)
TYP
    typst compile "$work/doc.typ" "$work/source.pdf"
    source_pdf="$work/source.pdf"
else
    echo "note: typst not found, falling back to the sample fixture"
    source_pdf="$fixtures/sample.pdf"
fi

echo "Signing $(basename "$source_pdf") ($(stat -c%s "$source_pdf") bytes)"
signed="$work/signed.pdf"
cargo run --quiet --example sign_simple -- \
    "$source_pdf" "$fixtures/signer.p12" test123 "$signed" 2>/dev/null \
    || fail "signing failed"

# --- poppler: signature validity and trust -----------------------------------

nssdb="$work/nssdb"
mkdir -p "$nssdb"
certutil -N -d "sql:$nssdb" --empty-password
certutil -A -d "sql:$nssdb" -n e2e-root -t "CT,CT,CT" -i "$fixtures/ca_cert.pem"
certutil -A -d "sql:$nssdb" -n e2e-intermediate -t ",," -i "$fixtures/intermediate_ca_cert.pem"

report="$work/pdfsig.txt"
pdfsig -nssdir "sql:$nssdb" -no-ocsp "$signed" > "$report" 2>&1 || true
cat "$report"

grep -q "Signature is Valid" "$report" || fail "poppler rejected the signature"
pass "poppler: signature is cryptographically valid"

grep -q "Certificate is Trusted" "$report" || fail "poppler could not build the trust chain"
pass "poppler: certificate chains to the trusted root"

# Guards against a ByteRange that leaves part of the file unsigned — the
# classic way a signature looks valid while covering almost nothing.
grep -q "Total document signed" "$report" || fail "signature does not cover the whole document"
pass "poppler: signature covers the entire document"

grep -q "ETSI.CAdES.detached" "$report" || fail "unexpected signature subfilter"
pass "poppler: PAdES subfilter reported"

# PAdES bans the CMS signingTime attribute, so the date reaches the reader only
# through /M. When nothing writes it, poppler falls back to the epoch.
grep -q "Signing Time:" "$report" || fail "poppler reported no signing time"
grep -q "Signing Time:.*1970" "$report" && fail "signing time fell back to the epoch — /M was not written"
pass "poppler: signing time read from /M, not the epoch"

# --- qpdf: structural integrity of the incremental update --------------------

qpdf --check "$signed" > "$work/qpdf.txt" 2>&1 \
    || { cat "$work/qpdf.txt"; fail "qpdf found structural errors"; }
pass "qpdf: no syntax or stream encoding errors"

# --- openssl: the chain, independent of poppler and of us --------------------

(cd "$work" && pdfsig -dump signed.pdf >/dev/null 2>&1)
openssl pkcs7 -inform DER -in "$work/signed.pdf.sig0" -print_certs -out "$work/embedded.pem" 2>/dev/null
openssl verify -CAfile "$fixtures/ca_cert.pem" \
    -untrusted "$fixtures/intermediate_ca_cert.pem" "$work/embedded.pem" >/dev/null \
    || fail "the certificate embedded in the CMS does not chain to the fixture root"
pass "openssl: embedded chain verifies independently"

# The CMS must ship the intermediate too, or a verifier holding only the root
# cannot build the path.
certs=$(grep -c "BEGIN CERTIFICATE" "$work/embedded.pem")
[ "$certs" -ge 2 ] || fail "expected the intermediate to be embedded, found $certs certificate(s)"
pass "openssl: $certs certificates embedded (signer + intermediate)"

# --- tampering must be detected ----------------------------------------------

# Flipping a byte inside the signed range must break the digest. Without this
# the checks above would still pass on a signature that covers nothing.
python3 - "$signed" "$work/tampered.pdf" <<'PY'
import re, sys
data = bytearray(open(sys.argv[1], "rb").read())
m = re.search(rb"/ByteRange\s*\[\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", data)
if not m:
    sys.exit("no /ByteRange found in the signed file")
offset = int(m.group(2)) // 2          # mid-way through the first signed span
data[offset] ^= 0xFF
open(sys.argv[2], "wb").write(data)
PY

pdfsig -nssdir "sql:$nssdb" -no-ocsp "$work/tampered.pdf" > "$work/tampered.txt" 2>&1 || true
grep -q "Signature is Valid" "$work/tampered.txt" \
    && { cat "$work/tampered.txt"; fail "a tampered document still validated"; }
pass "poppler: tampering inside the signed range is detected"

echo
echo "All end-to-end checks passed."
