#!/usr/bin/env bash
#
# End-to-end signing check against third-party tools.
#
# Every other test in this repo verifies underskrift's output with underskrift.
# This one signs a PDF and hands it to implementations that share no code with
# us: poppler for signature and trust validation, qpdf for structure, openssl
# for the certificate chain.
#
# Usage:
#   tests/e2e-verify.sh [document.pdf]
#
# With no argument a document is generated with typst, falling back to the
# committed sample fixture when typst is unavailable.
#
# Requires: pdfsig (poppler-utils), qpdf, certutil (libnss3-tools), openssl.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fixtures="$repo_root/tests/fixtures"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# --- presentation ------------------------------------------------------------

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
    bold=$'\033[1m'; dim=$'\033[2m'; red=$'\033[31m'; green=$'\033[32m'; reset=$'\033[0m'
else
    bold=''; dim=''; red=''; green=''; reset=''
fi

checks=0

section() { printf '\n%s▸ %s%s\n' "$bold" "$1" "$reset"; }
detail()  { printf '  %s%s%s\n' "$dim" "$1" "$reset"; }

ok() {
    checks=$((checks + 1))
    printf '  %s✓%s %s\n' "$green" "$reset" "$1"
}

# Failure prints the evidence: a bare "check failed" sends the reader digging
# for output the script already had in hand.
die() {
    printf '  %s✗ %s%s\n' "$red" "$1" "$reset" >&2
    if [ $# -gt 1 ] && [ -f "$2" ]; then
        printf '\n%s--- %s ---%s\n' "$dim" "$(basename "$2")" "$reset" >&2
        sed 's/^/  /' "$2" >&2
    fi
    exit 1
}

for tool in pdfsig qpdf certutil openssl; do
    command -v "$tool" >/dev/null || die "$tool not found on PATH"
done

# No check for the fixtures here on purpose: the cargo invocation below runs
# build.rs, which generates them when they are missing.

# --- the document under test -------------------------------------------------

if [ $# -ge 1 ]; then
    source_pdf="$1"
    origin="given on the command line"
elif command -v typst >/dev/null; then
    cat > "$work/doc.typ" <<'TYP'
#set page(width: 210mm, height: 297mm, margin: 20mm)
#set text(size: 11pt)
= Interoperability test document
Generated by Typst, signed by underskrift, verified by poppler.
#lorem(80)
TYP
    typst compile "$work/doc.typ" "$work/source.pdf"
    source_pdf="$work/source.pdf"
    origin="generated by $(typst --version)"
else
    source_pdf="$fixtures/sample.pdf"
    origin="sample fixture — typst not installed"
fi

printf '%sunderskrift end-to-end verification%s\n' "$bold" "$reset"
detail "document  $(basename "$source_pdf") — $origin"
detail "signer    tests/fixtures/signer.p12"

# --- signing -----------------------------------------------------------------

section "signing"
signed="$work/signed.pdf"
cargo run --quiet --example sign_simple -- \
    "$source_pdf" "$fixtures/signer.p12" test123 "$signed" > "$work/sign.txt" 2>&1 \
    || die "signing failed" "$work/sign.txt"

before=$(stat -c%s "$source_pdf")
after=$(stat -c%s "$signed")
ok "signed — $before → $after bytes (+$((after - before)))"

# --- poppler: signature validity and trust -----------------------------------

# The fixture CA is re-rolled by gen-test-fixtures.sh on every run, so the trust
# store is built from the chain that actually signed this file. Pointing it at a
# stale committed ca_cert.pem reports "Certificate issuer is unknown", which
# reads as a signing bug and is not one.
nssdb="$work/nssdb"
mkdir -p "$nssdb"
certutil -N -d "sql:$nssdb" --empty-password
certutil -A -d "sql:$nssdb" -n e2e-root -t "CT,CT,CT" -i "$fixtures/ca_cert.pem"
certutil -A -d "sql:$nssdb" -n e2e-intermediate -t ",," -i "$fixtures/intermediate_ca_cert.pem"

report="$work/pdfsig.txt"
pdfsig -nssdir "sql:$nssdb" -no-ocsp "$signed" > "$report" 2>&1 || true

section "poppler $(pdfsig -v 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"

grep -q "Signature is Valid" "$report" \
    || die "poppler rejected the signature" "$report"
ok "signature is cryptographically valid"

grep -q "Certificate is Trusted" "$report" \
    || die "poppler could not build the trust chain" "$report"
ok "certificate chains to the trusted root"

# Guards against a ByteRange that leaves part of the file unsigned — the classic
# way a signature looks valid while covering almost nothing.
grep -q "Total document signed" "$report" \
    || die "signature does not cover the whole document" "$report"
ok "signature covers the entire document — $(grep -oE 'Signed Ranges:.*' "$report")"

grep -q "ETSI.CAdES.detached" "$report" \
    || die "unexpected signature subfilter" "$report"
ok "PAdES subfilter reported — ETSI.CAdES.detached"

# PAdES bans the CMS signingTime attribute, so the date reaches the reader only
# through /M. When nothing writes it, poppler falls back to the epoch.
signing_time=$(sed -n 's/.*Signing Time: *//p' "$report" | head -1)
[ -n "$signing_time" ] || die "poppler reported no signing time" "$report"
case "$signing_time" in
    *1970*) die "signing time fell back to the epoch — /M was not written" "$report" ;;
esac
ok "signing time read from /M — $signing_time"

# --- qpdf: structural integrity of the incremental update --------------------

section "qpdf $(qpdf --version | grep -oE '[0-9]+\.[0-9.]+' | head -1)"
qpdf --check "$signed" > "$work/qpdf.txt" 2>&1 \
    || die "qpdf found structural errors" "$work/qpdf.txt"
ok "no syntax or stream encoding errors in the incremental update"

# --- openssl: the chain, independent of poppler and of us --------------------

section "openssl $(openssl version | awk '{print $2}')"
(cd "$work" && pdfsig -dump signed.pdf >/dev/null 2>&1)
openssl pkcs7 -inform DER -in "$work/signed.pdf.sig0" \
    -print_certs -out "$work/embedded.pem" 2>/dev/null

openssl verify -CAfile "$fixtures/ca_cert.pem" \
    -untrusted "$fixtures/intermediate_ca_cert.pem" \
    "$work/embedded.pem" > "$work/verify.txt" 2>&1 \
    || die "the certificate embedded in the CMS does not chain to the fixture root" "$work/verify.txt"
ok "embedded chain verifies independently of poppler"

# The CMS must ship the intermediate too, or a verifier holding only the root
# cannot build the path.
certs=$(grep -c "BEGIN CERTIFICATE" "$work/embedded.pem")
[ "$certs" -ge 2 ] \
    || die "expected the intermediate to be embedded, found $certs certificate(s)"
ok "$certs certificates embedded — signer + intermediate"

# --- enveloping CAdES: openssl must accept it and get the file back ----------

# The PDF path above proves the detached signature. This proves the attached
# one: openssl is told nothing about the format, and has to both validate the
# signature and reconstruct the original bytes from the envelope alone.
#
# tests/cms-tool.py appears throughout this section, and does no crypto: it only
# locates bytes in the DER so openssl can be the one doing the arithmetic.
cms_tool="$repo_root/tests/cms-tool.py"

envelope() {
    local mode="$1" out="$work/$1.p7m"
    cargo run --quiet --example sign_envelope -- \
        "$source_pdf" "$fixtures/signer.p12" test123 "$out" "$mode" \
        > "$work/$1.txt" 2>&1 || die "$mode enveloping signature failed" "$work/$1.txt"
}

verify_envelope() {
    openssl cms -verify -inform DER -in "$1" -CAfile "$fixtures/ca_cert.pem" \
        -out "${2:-/dev/null}" > "$work/cms-verify.txt" 2>&1
}

section "enveloping CAdES"
envelope single
ok "signed — $(stat -c%s "$source_pdf") → $(stat -c%s "$work/single.p7m") bytes"

verify_envelope "$work/single.p7m" "$work/recovered.pdf" \
    || die "openssl rejected the envelope" "$work/cms-verify.txt"
ok "openssl validates the signature and the chain"

cmp -s "$source_pdf" "$work/recovered.pdf" \
    || die "openssl recovered content that differs from the input"
ok "openssl recovered the original file byte for byte"

# The envelope is worthless if what comes out is no longer a usable document.
qpdf --check "$work/recovered.pdf" > "$work/recovered-qpdf.txt" 2>&1 \
    || die "the recovered PDF no longer parses" "$work/recovered-qpdf.txt"
ok "the recovered PDF still passes qpdf --check"

# A flipped byte inside the envelope must break it: otherwise the messageDigest
# attribute is not actually binding the content.
python3 - "$work/single.p7m" "$work/single-tampered.p7m" <<'PY'
import sys
data = bytearray(open(sys.argv[1], "rb").read())
data[len(data) // 2] ^= 0xFF
open(sys.argv[2], "wb").write(data)
PY
verify_envelope "$work/single-tampered.p7m" && die "a tampered envelope still validated"
ok "a flipped byte in the envelope is rejected"

# --- parallel signatures ------------------------------------------------------

# Two peers over the same content. openssl checks every SignerInfo, so breaking
# either one has to fail: that is what makes the passing case worth anything.
section "parallel signatures"
envelope parallel
signers=$(python3 "$cms_tool" count "$work/parallel.p7m")
[ "$signers" = "2" ] || die "expected 2 SignerInfos, found $signers"
ok "$signers signers in one SignedData"

verify_envelope "$work/parallel.p7m" "$work/recovered-parallel.bin" \
    || die "openssl rejected the two-signature envelope" "$work/cms-verify.txt"
cmp -s "$source_pdf" "$work/recovered-parallel.bin" \
    || die "content differs after a second signature was added"
ok "openssl validates both signatures, content unchanged"

for i in 0 1; do
    python3 "$cms_tool" break-signer "$work/parallel.p7m" "$work/broken-$i.p7m" "$i"
    verify_envelope "$work/broken-$i.p7m" \
        && die "openssl accepted an envelope whose signer $i is broken"
done
ok "breaking either signature is detected — neither is decorative"

# --- countersignature ---------------------------------------------------------

# RFC 5652 §11.4: the countersigner signs the target's signature value. openssl
# computes that digest here; nothing of ours is in the loop.
section "countersignature"
envelope countersigned
verify_envelope "$work/countersigned.p7m" \
    || die "openssl rejected the countersigned envelope" "$work/cms-verify.txt"
ok "the covered signature still validates under openssl"

openssl cms -cmsout -print -inform DER -in "$work/countersigned.p7m" > "$work/cmsout.txt" 2>&1
grep -q "countersignature (1.2.840.113549.1.9.6)" "$work/cmsout.txt" \
    || die "openssl does not see a countersignature attribute" "$work/cmsout.txt"
ok "openssl parses the attribute as a countersignature"

python3 "$cms_tool" signature "$work/countersigned.p7m" 0 "$work/target-sig.bin"
expected=$(openssl dgst -sha512 -r "$work/target-sig.bin" | awk '{print $1}')
actual=$(python3 "$cms_tool" countersig-digest "$work/countersigned.p7m" 0)
[ "$expected" = "$actual" ] \
    || die "countersignature messageDigest is not SHA-512 of the signature it covers
  openssl: $expected
  found:   $actual"
ok "messageDigest equals openssl's digest of the covered signature value"

# --- composing onto a foreign envelope ---------------------------------------

# The production case, with openssl standing in for whatever signed the file
# before it reached us: openssl signs, we add to it, openssl has to still be
# happy. Anything that re-encodes the bytes openssl signed fails right here.
section "foreign envelope (signed by openssl)"
foreign="$fixtures/foreign_envelope.p7m"
verify_envelope "$foreign" "$work/foreign-content.bin" \
    || die "openssl cannot verify its own envelope" "$work/cms-verify.txt"
cmp -s "$fixtures/sample.pdf" "$work/foreign-content.bin" \
    || die "the openssl fixture does not contain the sample document"
ok "openssl signed it; the content is the sample document"

for mode in parallel countersign; do
    cargo run --quiet --example compose_envelope -- \
        "$foreign" "$fixtures/signer.p12" test123 "$work/foreign-$mode.p7m" "$mode" \
        > "$work/compose-$mode.txt" 2>&1 || die "$mode composition failed" "$work/compose-$mode.txt"

    verify_envelope "$work/foreign-$mode.p7m" "$work/foreign-$mode.bin" \
        || die "openssl rejected its own signature after we added a $mode signature" \
               "$work/cms-verify.txt"
    cmp -s "$fixtures/sample.pdf" "$work/foreign-$mode.bin" \
        || die "$mode composition altered the enveloped content"
    ok "we added a $mode signature — openssl still validates the original"
done

# --- tampering must be detected ----------------------------------------------

# Without this, every check above would still pass on a signature that covers
# nothing at all.
section "tamper detection"
offset=$(python3 - "$signed" "$work/tampered.pdf" <<'PY'
import re, sys
data = bytearray(open(sys.argv[1], "rb").read())
m = re.search(rb"/ByteRange\s*\[\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", data)
if not m:
    sys.exit("no /ByteRange found in the signed file")
offset = int(m.group(2)) // 2          # mid-way through the first signed span
data[offset] ^= 0xFF
open(sys.argv[2], "wb").write(data)
print(offset)
PY
)

pdfsig -nssdir "sql:$nssdb" -no-ocsp "$work/tampered.pdf" > "$work/tampered.txt" 2>&1 || true
if grep -q "Signature is Valid" "$work/tampered.txt"; then
    die "a tampered document still validated" "$work/tampered.txt"
fi
ok "byte $offset flipped inside the signed range — $(sed -n 's/.*Signature Validation: *//p' "$work/tampered.txt" | head -1)"

printf '\n%s%d checks passed%s\n' "$green" "$checks" "$reset"
